#include "motor.h"

void DcMotor_Init(void)
{
    GPIO_setupPinDirection(DCMOTOR_INPUT1_PORT, DCMOTOR_INPUT1_FIRST_PIN, PIN_OUTPUT);
    GPIO_setupPinDirection(DCMOTOR_INPUT1_PORT, DCMOTOR_INPUT1_FIRST_PIN+1, PIN_OUTPUT);
    GPIO_setupPinDirection(DCMOTOR_ENABLE1_PORT, DCMOTOR_ENABLE1_PIN, PIN_OUTPUT);

    GPIO_writePin(DCMOTOR_INPUT1_PORT, DCMOTOR_INPUT1_FIRST_PIN  , STOP);
    GPIO_writePin(DCMOTOR_INPUT1_PORT, DCMOTOR_INPUT1_FIRST_PIN+1, STOP);


    #if DCMOTOR_TWO_MOTORS_INCLUDED
    GPIO_setupPinDirection(DCMOTOR_INPUT3_PORT, DCMOTOR_INPUT3_FIRST_PIN, PIN_OUTPUT);
    GPIO_setupPinDirection(DCMOTOR_INPUT3_PORT, DCMOTOR_INPUT3_FIRST_PIN+1, PIN_OUTPUT);
    GPIO_setupPinDirection(DCMOTOR_ENABLE3_PORT, DCMOTOR_ENABLE3_PIN, PIN_OUTPUT);

    GPIO_writePin(DCMOTOR_INPUT3_PORT, DCMOTOR_INPUT3_FIRST_PIN  , STOP);
    GPIO_writePin(DCMOTOR_INPUT3_PORT, DCMOTOR_INPUT3_FIRST_PIN+1, STOP);
    #endif
}

void DcMotor_Disable1(void)
{
    GPIO_writePin(DCMOTOR_ENABLE1_PORT, DCMOTOR_ENABLE1_PIN, !DCMOTOR_ENABLE1_LOGIC_HIGH);
}

void DcMotor_Rotate1(DcMotor_State state, uint8 speed)
{
    GPIO_writePort(DCMOTOR_INPUT1_PORT, GPIO_readPort(DCMOTOR_INPUT1_PORT)&~(0b11<<DCMOTOR_INPUT1_FIRST_PIN) | state);
    PWM_Timer0_Start(speed);
}

